# Generated by Django 4.1.6 on 2023-02-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="tag",
            field=models.ManyToManyField(to="produit.tag"),
        ),
    ]
