# Generated by Django 4.1.6 on 2023-02-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_date_creation"),
        ("produit", "0001_initial"),
        ("commande", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produit.produit",
            ),
        ),
    ]
