# Generated by Django 4.1.6 on 2023-02-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0002_tag"),
        ("commande", "0002_commande_client_commande_produit"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="tag",
            field=models.ManyToManyField(to="produit.tag"),
        ),
    ]
