# Generated by Django 4.1.6 on 2023-02-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commande", "0003_commande_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="commande", name="tag",),
    ]
